version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Sabertoothtech@1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080